# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the stable branch
  push:
    branches: [ testing ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ testing ]
    paths-ignore: [ '**/README.md' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Prerequisites
        run: |
          wget -q "https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.3/appimage-builder-1.0.3-x86_64.AppImage" -O appimage-builder ; chmod +x appimage-builder ; ./appimage-builder --appimage-extract &>/dev/null

          # add custom mksquashfs
          wget -q "https://github.com/mmtrt/WINE_AppImage/raw/master/runtime/mksquashfs" -O squashfs-root/usr/bin/mksquashfs

          # Add static appimage runtime
          mkdir -p appimage-build/prime
          wget -q "https://github.com/mmtrt/WINE_AppImage/raw/master/runtime/runtime-x86_64" -O appimage-build/prime/runtime-x86_64

          # force zstd format in appimagebuilder for appimages
          rm appimage-builder ; sed -i 's|xz|zstd|' squashfs-root/usr/lib/python3.8/site-packages/appimagebuilder/modules/prime/appimage_primer.py

          # version
          echo "BUILD_VER=test_g$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Build appimage
        run: squashfs-root/AppRun --recipe leagueoflegends.yml

      - name: Release
        uses: marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303
        with:
          title: leagueoflegends-test
          automatic_release_tag: test
          prerelease: false
          draft: false
          files: /home/runner/work/leagueoflegends_AppImage/leagueoflegends_AppImage/*.AppImage*
          repo_token: ${{ secrets.PATN }}
